export enum RequestStatus {
  DRAFT = "DRAFT",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  ACTIVE = "ACTIVE",
}

export enum BillingType {
  ONE_TIME = "ONE_TIME",
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
  YEARLY_MONTHLY = "YEARLY_MONTHLY",
}

export enum AuditAction {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  CANCEL = "CANCEL",
  UPLOAD = "UPLOAD",
  UPLOAD_APPROVAL = "UPLOAD_APPROVAL",
  SEND_APPROVAL = "SEND_APPROVAL",
  VERIFY = "VERIFY",
  STATUS_CHANGE = "STATUS_CHANGE",
}

export enum EntityType {
  REQUEST = "REQUEST",
  PROJECT = "PROJECT",
  RECEIPT = "RECEIPT",
  PROFILE = "PROFILE",
}
